# Generated by Django 3.1.3 on 2020-12-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summ', '0002_filesupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='FilesUpload',
        ),
    ]
